### ISSUE TITLE
Android: App crash due to error thrown 

### ISSUE THREAD

**Issue by jkpatel1463** [rainbowcreatures/FlashyWrappers#36]
Hello @rainbowcreatures 

Some times, Flashwrapper crashed in android. Here are my device details:
Android os Version: 23
Device: Moto G
Flashy Wrapper Version: 2.55

Error in flash builder:
```
Error: [FlashyWrappers error] java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Message android.os.Handler.obtainMessage()' on a null object reference
	at com.rainbowcreatures.FlashyWrappersAndroidHW.z.a(Unknown Source)
	at com.rainbowcreatures.FlashyWrappersAndroidHW.j.call(Unknown Source)
	at com.adobe.air.customHandler.callTimeoutFunction(Native Method)
	at com.adobe.air.customHandler.handleMessage(customHandler.java:22)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

	at com.rainbowcreatures::FWVideoEncoder/throwError()[C:\wamp\www\flashywrappers_svn\FW_src_stable\com\rainbowcreatures\FWVideoEncoder.as:1376]
	at com.rainbowcreatures::FWVideoEncoder/onStatus()[C:\wamp\www\flashywrappers_svn\FW_src_stable\com\rainbowcreatures\FWVideoEncoder.as:1370]

```

Try to search log at "/storage/emulated/0/Android/data/air.com.mycommUnity.app/files", but failed to find the files, because when i redirect to "/storage/emulated/" i don't have "0" directory in it. "/storage/emulated/" is completely empty

Here is the log from Android monitor:
```
09-23 16:10:29.422 24595-24595/? I/air.com.mycommUnity.app: Application.as - screenName: saveVideoScreen
09-23 16:10:29.473 24595-24595/? I/[FlashyWrappers]: Writing logfile to /storage/emulated/0/Android/data/air.com.mycommUnity.app/files
09-23 16:10:29.476 24595-24595/? I/[FlashyWrappers]: FW Log started
09-23 16:10:29.477 24595-24595/? I/[FlashyWrappers]: API level: 23
09-23 16:10:29.478 24595-24595/? I/[FlashyWrappers]: Device: titan_umtsds
09-23 16:10:29.479 24595-24595/? I/[FlashyWrappers]: Model: XT1068
09-23 16:10:29.479 24595-24595/? I/[FlashyWrappers]: Product: titan_retaildsds
09-23 16:10:29.521 24595-24595/? I/air.com.mycommUnity.app: SaveVideoScreen.as - setupVars: totalFrames: 670
09-23 16:10:29.522 24595-24595/? I/air.com.mycommUnity.app: _captureArea.width: 1152, _captureArea.height: 720
09-23 16:10:29.705 24595-24595/? I/air.com.mycommUnity.app: VideoConvertionHelper - onStatus: ready
09-23 16:10:29.731 24595-24595/? I/air.com.mycommUnity.app: Extension context initialized:[object ExtensionContext]
09-23 16:10:29.732 24595-24595/? I/air.com.mycommUnity.app: VideoConvertionHelper.as - onMixerStatus: ready
09-23 16:10:29.734 24595-24595/? I/System.out: IllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionIllegalArgumentExceptionFWSoundMixer_init() start
09-23 16:10:29.756 24595-24595/? I/System.out: FWSoundMixer_init()  end
09-23 16:10:29.775 24595-24595/? I/AndroidPermissionManager: virtual avmplus::StringConstants::StringConstant AndroidPermissionManager::checkPermission(Permission) permissionStatus = 0 
09-23 16:10:29.779 24595-24595/? I/AndroidPermissionManager: status = 564
09-23 16:10:29.779 24595-24595/? I/AndroidPermissionManager: virtual avmplus::StringConstants::StringConstant AndroidPermissionManager::checkPermission(Permission) permissionStatus = 564 
09-23 16:10:29.779 24595-24595/? I/AndroidPermissionManager: virtual avmplus::StringConstants::StringConstant AndroidPermissionManager::checkPermission(Permission) permissionStatus = 564 
09-23 16:10:29.779 24595-24595/? I/air.com.mycommUnity.app: Mixer ready, requesting Context3D...
09-23 16:10:29.792 24595-24595/? I/air.com.mycommUnity.app: SaveVideoScreen.as - onVideoInitCompleteHandler: 
09-23 16:10:29.793 24595-24595/? I/air.com.mycommUnity.app: file.url: app-storage:/images/communityApp9.png
09-23 16:10:29.795 24595-24595/? I/air.com.mycommUnity.app: file.url: app-storage:/images/communityApp10.png
09-23 16:10:29.796 24595-24595/? I/air.com.mycommUnity.app: file.url: app-storage:/images/communityApp11.png
09-23 16:10:29.797 24595-24595/? I/air.com.mycommUnity.app: file.url: app-storage:/images/communityApp12.png
09-23 16:10:29.912 24595-24595/? I/air.com.mycommUnity.app: loadTheImage: Complete: 
09-23 16:10:29.912 24595-24595/? I/air.com.mycommUnity.app: loadTheImage: Complete: 
09-23 16:10:29.913 24595-24595/? I/air.com.mycommUnity.app: loadTheImage: Complete: 
09-23 16:10:29.913 24595-24595/? I/air.com.mycommUnity.app: loadTheImage: Complete: 
09-23 16:10:30.955 24595-24595/? I/air.com.mycommUnity.app: SaveVideoScreen.as - startVideoRecord: 
09-23 16:10:30.958 24595-24595/? I/air.com.mycommUnity.app: SaveVideoScreen.as - initSound: 
09-23 16:10:30.968 24595-24595/? I/air.com.mycommUnity.app: Sound sound_0 doesn't exist, extracting...
09-23 16:10:31.039 24595-24595/? D/LOG_TAG: Setting sound name
09-23 16:10:31.039 24595-24595/? D/LOG_TAG: Getting rest of params
09-23 16:10:31.039 24595-24595/? D/LOG_TAG: Does sound exist?
09-23 16:10:31.039 24595-24595/? D/LOG_TAG: No, adding
09-23 16:10:31.039 24595-24595/? D/LOG_TAG: Reading sound ByteArray
09-23 16:10:31.043 24595-24595/? I/air.com.mycommUnity.app: Sound sound_1 doesn't exist, extracting...
09-23 16:10:31.102 24595-24595/? D/LOG_TAG: Setting sound name
09-23 16:10:31.102 24595-24595/? D/LOG_TAG: Getting rest of params
09-23 16:10:31.102 24595-24595/? D/LOG_TAG: Does sound exist?
09-23 16:10:31.102 24595-24595/? D/LOG_TAG: No, adding
09-23 16:10:31.102 24595-24595/? D/LOG_TAG: Reading sound ByteArray
09-23 16:10:31.105 24595-24595/? I/air.com.mycommUnity.app: Sound sound_2 doesn't exist, extracting...
09-23 16:10:31.172 24595-24595/? D/LOG_TAG: Setting sound name
09-23 16:10:31.172 24595-24595/? D/LOG_TAG: Getting rest of params
09-23 16:10:31.172 24595-24595/? D/LOG_TAG: Does sound exist?
09-23 16:10:31.173 24595-24595/? D/LOG_TAG: No, adding
09-23 16:10:31.173 24595-24595/? D/LOG_TAG: Reading sound ByteArray
09-23 16:10:31.175 24595-24595/? I/air.com.mycommUnity.app: Sound sound_3 doesn't exist, extracting...
09-23 16:10:31.239 24595-24595/? D/LOG_TAG: Setting sound name
09-23 16:10:31.239 24595-24595/? D/LOG_TAG: Getting rest of params
09-23 16:10:31.239 24595-24595/? D/LOG_TAG: Does sound exist?
09-23 16:10:31.239 24595-24595/? D/LOG_TAG: No, adding
09-23 16:10:31.239 24595-24595/? D/LOG_TAG: Reading sound ByteArray
09-23 16:10:31.249 24595-24595/? I/air.com.mycommUnity.app: Sound sound_4 doesn't exist, extracting...
09-23 16:10:31.306 24595-24595/? D/LOG_TAG: Setting sound name
09-23 16:10:31.307 24595-24595/? D/LOG_TAG: Getting rest of params
09-23 16:10:31.307 24595-24595/? D/LOG_TAG: Does sound exist?
09-23 16:10:31.307 24595-24595/? D/LOG_TAG: No, adding
09-23 16:10:31.307 24595-24595/? D/LOG_TAG: Reading sound ByteArray
09-23 16:10:31.309 24595-24595/? I/air.com.mycommUnity.app: Sound sound_5 doesn't exist, extracting...
09-23 16:10:31.381 24595-24595/? D/LOG_TAG: Setting sound name
09-23 16:10:31.381 24595-24595/? D/LOG_TAG: Getting rest of params
09-23 16:10:31.381 24595-24595/? D/LOG_TAG: Does sound exist?
09-23 16:10:31.381 24595-24595/? D/LOG_TAG: No, adding
09-23 16:10:31.381 24595-24595/? D/LOG_TAG: Reading sound ByteArray
09-23 16:10:31.383 24595-24595/? I/air.com.mycommUnity.app: Sound sound_6 doesn't exist, extracting...
09-23 16:10:31.480 24595-24595/? D/LOG_TAG: Setting sound name
09-23 16:10:31.480 24595-24595/? D/LOG_TAG: Getting rest of params
09-23 16:10:31.481 24595-24595/? D/LOG_TAG: Does sound exist?
09-23 16:10:31.481 24595-24595/? D/LOG_TAG: No, adding
09-23 16:10:31.481 24595-24595/? D/LOG_TAG: Reading sound ByteArray
09-23 16:10:31.484 24595-24595/? I/air.com.mycommUnity.app: Sound sound_7 doesn't exist, extracting...
09-23 16:10:31.557 24595-24595/? D/LOG_TAG: Setting sound name
09-23 16:10:31.558 24595-24595/? D/LOG_TAG: Getting rest of params
09-23 16:10:31.558 24595-24595/? D/LOG_TAG: Does sound exist?
09-23 16:10:31.558 24595-24595/? D/LOG_TAG: No, adding
09-23 16:10:31.558 24595-24595/? D/LOG_TAG: Reading sound ByteArray
09-23 16:10:31.562 24595-24595/? I/air.com.mycommUnity.app: Sound sound_8 doesn't exist, extracting...
09-23 16:10:31.649 24595-24595/? D/LOG_TAG: Setting sound name
09-23 16:10:31.649 24595-24595/? D/LOG_TAG: Getting rest of params
09-23 16:10:31.649 24595-24595/? D/LOG_TAG: Does sound exist?
09-23 16:10:31.649 24595-24595/? D/LOG_TAG: No, adding
09-23 16:10:31.649 24595-24595/? D/LOG_TAG: Reading sound ByteArray
09-23 16:10:31.653 24595-24595/? I/air.com.mycommUnity.app: Sound sound_9 doesn't exist, extracting...
09-23 16:10:31.710 24595-24595/? D/LOG_TAG: Setting sound name
09-23 16:10:31.710 24595-24595/? D/LOG_TAG: Getting rest of params
09-23 16:10:31.710 24595-24595/? D/LOG_TAG: Does sound exist?
09-23 16:10:31.710 24595-24595/? D/LOG_TAG: No, adding
09-23 16:10:31.710 24595-24595/? D/LOG_TAG: Reading sound ByteArray
09-23 16:10:31.712 24595-24595/? I/air.com.mycommUnity.app: SaveVideoScreen.as - recordVideo: 
09-23 16:10:31.722 24595-24595/? I/[FlashyWrappers]: Native microphone recording is OFF
09-23 16:10:31.725 24595-24595/? I/air.com.mycommUnity.app: [FlashyWrappers] Warning, dimensions 1280 x 720 WILL be ignored because realtime is set to true. In realtime mode on mobile, the OpenGL capture will keep either 1024 x 768 (in standard resolution) or 2048 x 1536 (in high resolution). If you want your captured video to be in different resolutions, you'll have to set realtime mode to false.
09-23 16:10:31.727 24595-24595/? I/[FlashyWrappers]: Listing available codecs...
09-23 16:10:31.786 24595-24595/? W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
09-23 16:10:31.809 24595-24595/? W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
09-23 16:10:31.835 24595-24595/? I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
09-23 16:10:31.841 24595-24595/? I/[FlashyWrappers]: OMX.google.mp3.decoder
09-23 16:10:31.842 24595-24595/? I/[FlashyWrappers]: OMX.google.amrnb.decoder
09-23 16:10:31.845 24595-24595/? I/[FlashyWrappers]: OMX.google.amrwb.decoder
09-23 16:10:31.846 24595-24595/? I/[FlashyWrappers]: OMX.google.aac.decoder
09-23 16:10:31.848 24595-24595/? I/[FlashyWrappers]: OMX.google.g711.alaw.decoder
09-23 16:10:31.849 24595-24595/? I/[FlashyWrappers]: OMX.google.g711.mlaw.decoder
09-23 16:10:31.849 24595-24595/? I/[FlashyWrappers]: OMX.google.vorbis.decoder
09-23 16:10:31.850 24595-24595/? I/[FlashyWrappers]: OMX.google.opus.decoder
09-23 16:10:31.851 24595-24595/? I/[FlashyWrappers]: OMX.google.raw.decoder
09-23 16:10:31.852 24595-24595/? I/[FlashyWrappers]: OMX.google.aac.encoder
09-23 16:10:31.852 24595-24595/? I/[FlashyWrappers]: OMX.google.amrnb.encoder
09-23 16:10:31.853 24595-24595/? I/[FlashyWrappers]: OMX.google.amrwb.encoder
09-23 16:10:31.854 24595-24595/? I/[FlashyWrappers]: OMX.google.flac.encoder
09-23 16:10:31.854 24595-24595/? I/[FlashyWrappers]: OMX.google.gsm.decoder
09-23 16:10:31.855 24595-24595/? I/[FlashyWrappers]: OMX.qcom.video.encoder.avc
09-23 16:10:31.856 24595-24595/? I/[FlashyWrappers]: OMX.qcom.video.encoder.mpeg4
09-23 16:10:31.857 24595-24595/? I/[FlashyWrappers]: OMX.qcom.video.encoder.h263
09-23 16:10:31.858 24595-24595/? I/[FlashyWrappers]: OMX.qcom.video.decoder.avc
09-23 16:10:31.859 24595-24595/? I/[FlashyWrappers]: OMX.qcom.video.decoder.mpeg2
09-23 16:10:31.860 24595-24595/? I/[FlashyWrappers]: OMX.qcom.video.decoder.mpeg4
09-23 16:10:31.860 24595-24595/? I/[FlashyWrappers]: OMX.qcom.video.decoder.h263
09-23 16:10:31.862 24595-24595/? I/[FlashyWrappers]: OMX.google.mpeg4.decoder
09-23 16:10:31.863 24595-24595/? I/[FlashyWrappers]: OMX.google.h263.decoder
09-23 16:10:31.863 24595-24595/? I/[FlashyWrappers]: OMX.google.h264.decoder
09-23 16:10:31.866 24595-24595/? I/[FlashyWrappers]: OMX.google.hevc.decoder
09-23 16:10:31.867 24595-24595/? I/[FlashyWrappers]: OMX.google.vp8.decoder
09-23 16:10:31.867 24595-24595/? I/[FlashyWrappers]: OMX.google.vp9.decoder
09-23 16:10:31.868 24595-24595/? I/[FlashyWrappers]: OMX.google.h263.encoder
09-23 16:10:31.869 24595-24595/? I/[FlashyWrappers]: OMX.google.h264.encoder
09-23 16:10:31.870 24595-24595/? I/[FlashyWrappers]: OMX.google.mpeg4.encoder
09-23 16:10:31.870 24595-24595/? I/[FlashyWrappers]: OMX.google.vp8.encoder
09-23 16:10:31.897 24595-24595/? I/air.com.mycommUnity.app: [FlashyWrappers] Merged file path: /storage/emulated/0/Android/data/air.com.mycommUnity.app/files/video_merged.mp4
09-23 16:10:31.898 24595-24595/? I/air.com.mycommUnity.app: [FlashyWrappers] Erasing old merged file
09-23 16:10:31.909 24595-24595/? I/[FlashyWrappers]: Setting capturing profile for AIR
09-23 16:10:31.910 24595-24595/? I/[FlashyWrappers]: Starting the composer thread...
09-23 16:10:31.925 24595-24595/? I/[FlashyWrappers]: Composer thread started...
09-23 16:10:31.926 24595-24595/? I/[FlashyWrappers]: Video capture rect: 0 x 0
09-23 16:10:31.938 24595-24595/? I/[FlashyWrappers]: frame step is 0.0
09-23 16:10:31.938 24595-25577/? I/[FlashyWrappers]: Starting composerRunnable...
09-23 16:10:31.939 24595-24595/? I/[FlashyWrappers]: mWidth:1280 mHeight:720mBitRate:1000000
09-23 16:10:31.939 24595-24595/? I/[FlashyWrappers]: Shared context requested, finding out which version it is...
09-23 16:10:31.940 24595-24595/? I/[FlashyWrappers]: GLES version: OpenGL ES 3.0 V@136.0 AU@ (GIT@I3193f6e94a)
09-23 16:10:31.940 24595-24595/? I/[FlashyWrappers]: Parsed GLES version (hopefully matches string above): 3
09-23 16:10:31.941 24595-24595/? I/[FlashyWrappers]: GLES renderer: Adreno (TM) 305
09-23 16:10:31.941 24595-24595/? I/[FlashyWrappers]: GL_MAX_VERTEX_ATTRIBS: 16
09-23 16:10:31.942 24595-24595/? I/[FlashyWrappers]: Sending START message to composer thread...
09-23 16:10:31.942 24595-24595/? I/[FlashyWrappers]: composerRunnable:com.rainbowcreatures.FlashyWrappersAndroidHW.af@bdd8c8
09-23 16:10:31.943 24595-24595/? I/[FlashyWrappers]: handler:null
09-23 16:10:31.946 24595-24595/? I/[FlashyWrappers]: Initialization was not OK, capturing will be disabled
09-23 16:10:31.949 24595-25577/? I/[FlashyWrappers]: Starting composerRunnable loop...
09-23 16:10:31.958 24595-24595/? W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Message android.os.Handler.obtainMessage()' on a null object reference
09-23 16:10:31.958 24595-24595/? W/System.err:     at com.rainbowcreatures.FlashyWrappersAndroidHW.z.a(Unknown Source)
09-23 16:10:31.958 24595-24595/? W/System.err:     at com.rainbowcreatures.FlashyWrappersAndroidHW.j.call(Unknown Source)
09-23 16:10:31.958 24595-24595/? W/System.err:     at com.adobe.air.customHandler.callTimeoutFunction(Native Method)
09-23 16:10:31.958 24595-24595/? W/System.err:     at com.adobe.air.customHandler.handleMessage(customHandler.java:22)
09-23 16:10:31.958 24595-24595/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
09-23 16:10:31.958 24595-24595/? W/System.err:     at android.os.Looper.loop(Looper.java:148)
09-23 16:10:31.958 24595-24595/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5443)
09-23 16:10:31.958 24595-24595/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-23 16:10:31.958 24595-24595/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
09-23 16:10:31.958 24595-24595/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
09-23 16:10:31.959 24595-24595/? I/air.com.mycommUnity.app: VideoConvertionHelper - onStatus: started
09-23 16:10:31.960 24595-24595/? I/air.com.mycommUnity.app: BackgroundSound: null
09-23 16:10:31.970 24595-24595/? I/[FlashyWrappers]: audio: addAudioFrameShorts with 8192 bytes
09-23 16:10:31.972 24595-24595/? I/[FlashyWrappers]: addAudioFrame took 1 ms
09-23 16:10:31.983 24595-24595/? I/[FlashyWrappers]: Forcing PTS mode 2
09-23 16:10:31.984 24595-25501/? W/AudioTrack: releaseBuffer() track 0xb955fc40 disabled due to previous underrun, restarting
09-23 16:10:31.984 390-1049/? D/audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
09-23 16:10:31.985 390-1049/? D/audio_hw_fm: audio_extn_fm_set_parameters: Inside
09-23 16:10:31.985 390-1049/? V/audio_hw_fm: audio_extn_fm_set_parameters: enter
09-23 16:10:31.985 390-1049/? V/audio_hw_fm: audio_extn_fm_set_parameters: exit
09-23 16:10:31.985 24595-24595/? I/[FlashyWrappers]: Forcing framedrop mode 2, frame step is 41.66666793823242
09-23 16:10:31.996 390-1048/? D/audio_hw_primary: select_devices: out_snd_device(2: speaker) in_snd_device(0: none)
09-23 16:10:31.996 390-1048/? D/msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(15)
09-23 16:10:31.997 390-1048/? D/ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 15, path =  0
09-23 16:10:31.997 390-1048/? D/ACDB-LOADER: ACDB -> send_adm_topology
09-23 16:10:31.997 390-1048/? D/ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
09-23 16:10:31.997 390-1048/? D/ACDB-LOADER: ACDB -> send_audtable
09-23 16:10:31.997 390-1048/? D/ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
09-23 16:10:31.997 390-1048/? D/ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_CAL
09-23 16:10:31.997 390-1048/? D/ACDB-LOADER: ACDB -> send_audvoltable
09-23 16:10:31.997 390-1048/? D/ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE
09-23 16:10:31.997 390-1048/? D/ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
09-23 16:10:31.997 390-1048/? D/ACDB-LOADER: ACDB -> send_afe_cal
09-23 16:10:31.997 390-1048/? D/ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
                                             
                                             
                                             [ 09-23 16:10:31.997   390: 1048 D/         ]
                                             Failed to fetch the lookup information of the device 0000000F 
09-23 16:10:31.997 390-1048/? D/ACDB-LOADER: ACDB -> AUDIO_SET_AFE_CAL
09-23 16:10:31.997 390-1048/? D/audio_hw_primary: enable_snd_device: snd_device(2: speaker)
09-23 16:10:32.004 390-1048/? D/audio_hw_primary: enable_audio_route: apply and update mixer path: low-latency-playback speaker
09-23 16:10:32.015 390-1049/? D/AudioFlinger: mixer(0xb4309008) throttle end: throttle time(10)
09-23 16:10:33.335 406-602/? I/ThermalEngine: Sensor:batt_therm:36500 mC
09-23 16:10:33.347 406-603/? I/ThermalEngine: Sensor:xo_therm_pu2:43000 mC
09-23 16:10:34.325 818-873/? D/TCMD: NL - Read 56 bytes from update socket.
```

Here is code to start the recording:
```
if(Utils.isIOS)
{
	_fwEncoder.start(24, FWVideoEncoder.AUDIO_STEREO);
}
else
{
	_fwEncoder.setDimensions(_container.stage.stageWidth, _container.stage.stageHeight);
	_fwEncoder.start(24, FWVideoEncoder.AUDIO_STEREO, false);
	_fwEncoder.forcePTSMode(FWVideoEncoder.PTS_REALTIME);   //  force software mode to work in realtime      
	_fwEncoder.forceFramedropMode(FWVideoEncoder.FRAMEDROP_ON);   //  force software mode to work in realtime
}
```

Code for init the encoder:
```
_fwEncoder=FWVideoEncoder.getInstance(_container);
_fwEncoder.setLogging(FWVideoEncoder.LOGGING_VERBOSE);
_fwEncoder.addEventListener(StatusEvent.STATUS, onStatus);
_fwEncoder.load();
```

**Comment by rainbowcreatures** [comment]
This should be fixed in 2.6, closing.
